### Create a New Contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Patrick",
  "lastName": "Star",
  "email": "patrickstar@example.com",
  "favoriteColor": "pink",
  "birthday": "01/01/2001"
}

### Update an existing contact by ID
PUT http://localhost:3000/contacts/65187081bd70f4457da2b6f6
Content-Type: application/json

{
  "firstName": "SpongeBob",
  "lastName": "SquarePants",
  "email": "spongebobsquarepants@example.com"
}

### Delete an existing contact by ID
DELETE http://localhost:3000/contacts/65187081bd70f4457da2b6f6